apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps-app
spec:
  loadBalancerIP: 172.17.0.9
  ports:
  - port: 20
    protocol: TCP
    name: ftp-data
  - port: 21
    protocol: TCP
    name: ftps
  - port: 21000
    protocol: TCP
    name: ftp-transfer
  selector:
    app: ftps-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ftps-image
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /root/script/liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        imagePullPolicy: Never
        env:
        - name: FTP_USER
          value: admin
        - name: FTP_PASSWORD
          value: admin
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000