apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/allow-shared-ip: share-ip 
spec:
  type: LoadBalancer
  loadBalancerIP: IPex
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: grafana-image
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /root/srcs/liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 3000
        imagePullPolicy: Never