apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin-app
  annotations:
    metallb.universe.tf/allow-shared-ip: share-ip
spec:
  type: LoadBalancer
  loadBalancerIP: IPex
  ports:
  - port: 5000
    protocol: TCP
    name: http
  selector:
    app: phpmyadmin-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /root/srcs/liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 5000
        imagePullPolicy: Never